### ISSUE TITLE
Speed not stored / recalled correctly after power cycle

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#54]

**Comment by matrix12x** [comment]
This bug existed in my versions as well. Honestly I could not get it to recall speed with the patch. The bug probably exists in GliGli's original code.

Also, I don't think Arp/seq speed should be a patch level parameter. Because if it was, then when you change patches, arp/seq speed would change. So imagine you are playing a patch with the sequencer playing, and you go to audition different patches with that seq, if speed was a patch level parameter, then the speed would change.

On my unit on Alpha 9 (monad previous) speed always starts at zero on power on.

**Comment by image-et-son** [comment]
Finally found it. There were some remnants of the speed parameter as part of the patch and the transfer of the parameter to a settings parameter was only half implemented.
